# -*- coding: utf-8 -*-
"""Uberon_csv_to_yaml_json.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-rULSQhrHMjtYcqeLsYKyW-bJf__05eU
"""

import csv
import yaml
import re

"""Converting csv to yaml"""

def extract_uberon_id(full_id):
    return full_id.split("/")[-1]

import csv
import yaml
import re


def parse_synonym_entry(entry):
    entry = entry.strip()

    match = re.match(r"(.+?)\s*\[(.+?)\]$", entry)
    if not match:
        return None

    value = match.group(1).strip()
    ref = match.group(2).strip()

    # DB:ID case
    if ":" in ref and not ref.startswith("http"):
        origin_name, origin_id = ref.split(":", 1)
        return value, origin_name, origin_id

    # URL case
    if ref.startswith("http"):
        return value, "URL", ref

    return None


def csv_to_yaml_synonyms(csv_filepath, yaml_filepath):

    terms = []
    seen = set()

    with open(csv_filepath, mode='r', encoding='utf-8-sig') as csvfile:
        reader = csv.DictReader(csvfile)

        for row in reader:

            synonym_fields = [
                row.get('exact_synonyms', ''),
                row.get('related_synonyms', '')
            ]

            for field in synonym_fields:
                if not field:
                    continue

                for entry in field.split("|"):

                  raw_entry = entry.strip()

                  parsed = parse_synonym_entry(raw_entry)

                  if not parsed:
                      continue

                  value, origin_name, origin_id = parsed

                  key = (origin_name, origin_id, value)

                  if key in seen:
                      continue
                  seen.add(key)

                  synonym_term = {
                      'origin_name': origin_name,
                      'origin_id': origin_id,
                      'origin_version': '1',
                      'value': value,
                      'definition': '',
                      # Store FULL original synonym entry here
                      'external_references': raw_entry
                  }

                  terms.append(synonym_term)

    with open(yaml_filepath, 'w', encoding='utf-8') as yamlfile:
        yaml.dump({'terms': terms}, yamlfile, sort_keys=False, allow_unicode=True)

    print("Synonym YAML file created:", yaml_filepath)


# Example call
csv_to_yaml_synonyms("human_view_clean.csv", "uberon_synonyms.yaml")

# sample_syn = 'nucleus tegmentales anteriores [FMA:TA]|anterior tegmental nuclei [FMA:72435]|nucleus tegmenti ventralis [NeuroNames:518]|nucleus of Gudden [MA:0001031]|ganglion profundum tegmenti [NeuroNames:518]|nucleus ventralis tegmenti [NeuroNames:518]|rostral tegmental nucleus [TAO:0000275]|ganglion tegmenti ventrale [NeuroNames:518]|nucleus ventralis tegmenti (Gudden) [NeuroNames:518]|anterior tegmental nucleus [http://www.medilexicon.com/medicaldictionary.php?t=61761]|anterior tegmental nucleus [FMA:72435]|nucleus tegmentalis anterior [FMA:TA]'

# parse_synonym_entry(sample_syn)

"""Final version for Uberon synonyms json generation which donot have the uberon origin name (as those already exist in the database)

"""

import yaml
import json
import secrets
from datetime import datetime, timezone


def make_nanoid(size=6):
    alphabet = "abcdefghijkmnopqrstuvwxyzABCDEFGHJKMNPQRSTUVWXYZ0123456789"
    return ''.join(secrets.choice(alphabet) for _ in range(size))


def make_commit():
    return f"CDEPV-{datetime.now(timezone.utc).strftime('%Y%m%d')}"


def yaml_to_json_rows(yaml_path, json_output_path):

    with open(yaml_path, "r", encoding="utf-8") as f:
        data = yaml.safe_load(f)

    terms = data.get("terms", [])
    rows = []

    for term in terms:
      if term.get("origin_name") == "UBERON": #terms with origin names like UBERONREF or URLS from github that have uberon origins are inserted as new nodes in the db, because upon cross checking those synonyms did not exist in the uberon_terms.json as part of the main terms set.
        continue

      value = term.get("value", "")
      handle = value.replace(" ", "_")

      row = {
          "_commit": make_commit(),
          "handle": handle,
          "nanoid": make_nanoid(),
          "origin_name": term.get("origin_name"),
          "origin_id": term.get("origin_id"),
          "origin_version": term.get("origin_version"),
          "origin_definition": term.get("definition", ""),
          "value": value,
          "external_references": term.get("external_references", "")
      }

      rows.append(row)

    with open(json_output_path, "w", encoding="utf-8") as f:
        json.dump(rows, f, ensure_ascii=False)

    print(f"Generated {len(rows)} rows.")
    print(f"Saved to {json_output_path}")


# Run
yaml_to_json_rows("uberon_synonyms new.yaml", "uberon_synonyms.json")

